#%RAML 1.0 NamedExample
200-ex:
  [
                {
                  "bookid": 1,
                  "bookversion": "v1.1",
                  "bookAuthName": {
                    "AuthFname": "shubham",
                    "AuthLname": "rendalkar"
                  }
                },
                {
                  "bookid": 2,
                  "bookversion": "v1.1",
                  "bookAuthName": {
                    "AuthFname": "shubham1",
                    "AuthLname": "rendalkar1"
                  }
                  }
                
  ]   