#%RAML 1.0 NamedExample
200-ex:
   [
                {
                  "notebookid": 1,
                  "notebookparameter": {
                    "nsize": "A4",
                    "pages": "200"
                  }
                },
                {
                  "notebookid": 2,
                  "notebookparameter": {
                    "nsize": "A3",
                    "pages": "100"
                  }
                }
  ]   